spring:
  resources:
    static-locations: file:./index/, file:./static/,/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/public/
  redis:
    embedded:
      enabled: true  # 使用内置的redis,不建议在生产环境中使用.
      host: 127.0.0.1
      port: 6370
      data-path: ./data/redis
    host: 127.0.0.1
    port: 6370
    lettuce:
      pool:
        max-active: 1024
    timeout: 20s
  r2dbc:
    url: r2dbc:h2:file:///./data/h2db/jetlinks
    username: sa
    password:
    pool:
      max-size: 32
easyorm:
  default-schema: PUBLIC # 数据库默认的schema
  dialect: h2 #数据库方言
elasticsearch:
  embedded:
    enabled: true # 为true时使用内嵌的elasticsearch,不建议在生产环境中使用
    data-path: ./data/elasticsearch
    port: 9201
    host: 0.0.0.0
  client:
    host: localhost
    port: 9201
    max-conn-total: 128
    connect-timeout: 5000
    socket-timeout: 5000
    connection-request-timeout: 8000
  index:
    default-strategy: time-by-month #默认es的索引按月进行分表, direct则为直接操作索引.
    settings:
      number-of-shards: 1 # es 分片数量
      number-of-replicas: 0 # 副本数量
device:
  message:
    writer:
      time-series:
        enabled: true #写出设备消息数据到elasticsearch
logging:
  level:
    com.github.tonivade: error